services:
  postgrestmpfsfsyncoff:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data/
    command:
      - "postgres"
      - "-c"
      - "fsync=off"
      - "-c"
      - "max_connections=1100"
    ports:
      - "5432:5432"
  postgresfsyncoff:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "fsync=off"
      - "-c"
      - "max_connections=1100"
    ports:
      - "5433:5432"
  postgrestmpfs:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data/
    command:
      - "postgres"
      - "-c"
      - "max_connections=1100"
    ports:
      - "5435:5432"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_connections=1100"
    ports:
      - "5434:5432"